server:
  error:
    include-message: always
  servlet:
    context-path: /eshop
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/eshop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        show_sql: false
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
logging:
  level:
    root: ERROR
    '[formation.sopra.formationSpringBoot.restcontroller.ClientRestController]': INFO    
  file:
    name: logs.log







 
 #1 TRACE   
 #2 DEBUG   
 #3 INFO
 #4 WARN
 #5 ERROR
 #6 FATAL
 #7 OFF   